version: '2.1'

services:
  notes-api:
    container_name: notes-api
    restart: always
    image: notes-api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    volumes:
      - .:/app
    links:
      - postgres
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - '5432:5432'