FROM node:10.15-alpine

ENV NODE_ENV development
ENV SERVER_PORT=${SERVER_PORT}

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install --development --silent && mv node_modules ../

COPY . .

EXPOSE SERVER_PORT

RUN npm install -g nodemon

CMD ["nodemon", "./server/index.js"]