version: '2.1'

services:
  notes-api:
    container_name: notes-api
    restart: always
    image: notes-api
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      DEBUG_SERVER_PORT: ${DEBUG_SERVER_PORT}
      SWAGGER_URL: ${SWAGGER_URL}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${DEBUG_SERVER_PORT}:${DEBUG_SERVER_PORT}"
    volumes:
      - ./server:${WORKDIR}/server
    links:
      - postgres
    command:
      - nodemon
      - "--inspect=0.0.0.0"
      - "./server/index.js"
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"