version: '2.1'

services:
  notes-api:
    container_name: notes-api
    restart: always
    image: notes-api
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      NODE_ENV: development
      SERVER_PORT:
    ports:
      - "3020:3020"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    links:
      - postgres
    mem_limit: 500M
    command:
      - nodemon
      - "--inspect=0.0.0.0"
      - "./server/index.js"
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    mem_limit: 500M